rm(list = ls())
library(sqldf)
DF <- read.csv.sql("household_power_consumption.txt", sql = 'select * from file where date = "1/2/2007" or date = "2/2/2007"', header = TRUE, sep = ";")
png(file="plot3.png")
DF$Combined <- paste(DF$Date, DF$Time)
DF$CombinedFormated <- strptime(DF$Combined, format = "%d/%m/%Y %H:%M:%S")
plot(DF$CombinedFormated, DF$Sub_metering_1, xlab = "", ylab ="Energy sub metering", type = "l", col="black")
lines(DF$CombinedFormated, DF$Sub_metering_2, col="red")
lines(DF$CombinedFormated, DF$Sub_metering_3, col="blue")
legend("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), pch = "-")
dev.off()